### PR TITLE
Fix the package prefix and allow creation of binary (arch) rpms on Centos

### PR DESCRIPTION
**Pull request by divereigh**
The first two changes are just dealing with the double hyphen that gets used if no --prefix is specified. It could be done this way, or the default could be changed from 'perl-' to just 'perl'. This actually matches the docs.

The third change may just be a CentOS thing. Unless the --install-base option is used (which forces a whole load of other changes on CentOS, like the module going under a subdir of the perl version), the rpmbuild can't find the files that get put under the /auto/ directory.

### CODE REVIEW

**Comment by SBECK-github** [comment]
The first two patches I'm completely fine with.  However, I'm completely sure about the 3rd patch.

The first part (near line 1952), you classify a *.so file as a .pm file.  I can see two results from that.  The first is that all .pm files get checked for requirements and what they provide, and I don't see any useful reason to check .so files in that way.  The second (which I believe is what you are doing) is to set the arch_install flag (so the package will include the architecture instead of being noarch).  Am I understanding correctly?

In this case, I do not want to apply the patch directly (because a .so file is NOT a .pm file), but I'll add an additional test to the _categorize_files method and if it finds a .so, I'll set the arch_install flag.

If I am correctly understanding your line 1952 patch, then I also understand the remainder of your patch.

Could you confirm that I'm understanding you correctly, and if so, I'll apply the changes you suggest.

Thanks

**Comment by divereigh** [comment]
Yes you are completely correct. The whole intention behind the third patch is to set the arch_inst flag when it finds a .so file and yes I agree adding a .so file to the list of .pm files is a bit dumb. So your method is much better.

**Comment by SBECK-github** [comment]
I've checked in a version which should address both issues.  It includes the first parts of your patch, and a modified version of your third patch.  Let me know if it works as desired.
Thanks

**Comment by divereigh** [comment]
Yes it's works well, thank you.

Also want to say what a great bit of code you have written here - extremely useful!

**Pull request closed without merging**
